# Generated by Django 3.2.9 on 2022-03-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='crt_name',
        ),
    ]
