# Generated by Django 3.2.9 on 2022-03-10 14:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_chat', '0004_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notification',
            new_name='notifications',
        ),
    ]
